

version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database.db
    volumes:
      - db_data:/var/lib/postgresql/data 
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    environment:
      PRODUCTION: True
      DB_SERVICE: db 
      DATABASE_URL: 'postgresql://sigekria_api:root@root:5432/database.db' # Use service name "db" as hostname
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db 

volumes:
  db_data:
